blocks-broken=<prefix>Du hast heute {current_blocks}/{max_blocks} Blöcke gefällt.</prefix>
consoleName=Konsole
disabled=<prefix_negative>Auto-Baumfällen deaktiviert.</prefix_negative>
disabledByOther=<prefix_negative>Auto-Baumfällen deaktiviert durch {player}.</prefix_negative>
disabledForOther=<prefix_negative>Auto-Baumfällen deaktiviert für {player}</prefix_negative>
enabled=<prefix>Auto-Baumfällen aktiviert.</prefix>
enabledByOther=<prefix>Auto-Baumfällen aktiviert durch {player}</prefix>
enabledForOther=<prefix>Auto-Baumfällen aktiviert für {player}</prefix>
hitmaxblock=<prefix_negative>Du hast dein tägliches Blocklimit zum Auto-Baumfällen erreicht.</prefix_negative>
hitmaxusage=<prefix_negative>Du hast dein Tageslimit zum Auto-Baumfällen erreicht.</prefix_negative>
no-permission=<prefix_negative>Dazu hast du keine Berechtigung</prefix_negative>
usage=<prefix>Du hast Auto-Baumfällen heute {current_uses}/{max_uses} mal verwendet.</prefix>
noResidencePermissions=<red>Du hast keine Berechtigung AutoTreeChop hier zu nutzen.</red>
only-players=<red>Dieser Befehl kann nur von Spielern benutzt werden.</red>
stillInCooldown=<yellow>AutoTreeChop kühlt sich ab. Bitte warte {cooldown_time} seconds.</yellow>
confirmationRequiredIdle=<yellow>AutoTreeChop wurde in der letzten Zeit nicht benutzt. Fälle ein Stamm erneut (oder<white>/atc confirm</white>) inerhalb <white>{timeout}s</white> to confirm.</yellow>
confirmationRequiredNoLeaves=<yellow>Keine Blätter in der Nähe erkannt. Dieser Baumstamm könnte von Spielern plaziert sein. Schlag wieder (oder <white>/atc bestätige</white>) innerhalb von <white>{timeout}s</white> um zu bestätigen.</yellow>
confirmationRequiredBoth=<yellow>AutoTreeChop wurde längere Zeit nicht verwendet und in der Nähe wurden keine Blätter erkannt. Schlag nochmal (oder <white>/atc bestätige</white>) innerhalb von <white>{timeout}s</white> um zu bestätigen.</yellow>
confirmationSuccess=<green>Erfolgreich bestätigt. AutoTreeChop ist nun aktiv.</green>
noPendingConfirmation=<red>Es gibt keine vorhandende AutoTreeChop-Bestätigung.</red>
sneakEnabled=<green>AutoTreeChop wurde beim Schleichen aktiviert.</green>
sneakDisabled=<yellow>AutoTreeChop wurde nach Ende des Schleichens deaktiviert.</yellow>
aboutHeader=<green><bold>AutoTreeChop</bold></green><gray> - <aqua>v{version}</aqua> vom MilkTeaMC-Team und Contributors</gray>
aboutLicense=<gray>Lizenz: GNU General Public License v3.0 (GPL-3.0)</gray>
aboutGithub=<gray>GitHub: <white>https://github.com/milkteamc/autotreechop</white></gray>
aboutModrinth=<gray>Modrinth: <white>https://modrinth.com/plugin/autotreechop</white></gray>
