blocks-broken=<gray>Bloques rotos hoy: {current_blocks}/{max_blocks}</gray>
consoleName=Consola
disabled=<yellow>AutoTreeChop desactivado.</yellow>
disabledByOther=<yellow>AutoTreeChop fue desactivado por {player}. </yellow>
disabledForOther=<yellow>AutoTreeChop fue desactivado para {player}. </yellow>
enabled=<green>AutoTreeChop habilitado. </green>
enabledByOther=<green>AutoTreeChop fue activado por {player}. </green>
enabledForOther=<green>AutoTreeChop se activó para {player}. </green>
hitmaxblock=<red>Has alcanzado tu límite diario de ruptura de bloques. </red>
hitmaxusage=<red>Has alcanzado tu límite de uso diario. </red>
no-permission=<red>No tienes permiso para realizar esta acción. </red>
usage=<gray>Daily AutoTreeChop usó: {current_uses}/{max_uses}</gray>
noResidencePermissions=<red>No tienes permiso para usar AutoTreeChop aquí. </red>
stillInCooldown=<yellow>AutoTreeChop se está enfriando. Por favor, espere {cooldown_time} segundos. </yellow>
only-players=<red>Este comando solo puede ser utilizado por jugadores. </red>
confirmationRequiredIdle=<yellow>AutoTreeChop no se ha utilizado recientemente. Recorte un registro de nuevo (o <white>/atc confirm</white>) dentro de <white>{timeout}s</white> para confirmar. </yellow>
confirmationRequiredNoLeaves=<yellow>No se detectó ninguna hoja cercana. Este registro puede estar colocado por el jugador. Cortar otra vez (o <white>/atc confirm</white>) dentro de <white>{timeout}s</white> para confirmar. </yellow>
confirmationRequiredBoth=<yellow>AutoTreeChop no se ha utilizado recientemente y no se han detectado hojas cercanas. Cortar otra vez (o <white>/atc confirm</white>) dentro de <white>{timeout}s</white> para confirmar. </yellow>
confirmationSuccess=<green>Confirmación exitosa. AutoTreeChop ahora está activo. </green>
noPendingConfirmation=<red>No hay ninguna confirmación pendiente de AutoTreeChop. </red>
sneakEnabled=<green>Se habilita la opción de seguimiento automático mientras se oculta. </green>
sneakDisabled=<yellow>La opción de hacer clic automáticamente se deshabilitó después de parar. </yellow>
aboutHeader=<green><bold>AutoTreeChop</bold></green><gray> - <aqua>v{versión}</aqua> por el equipo de MilkTeaMC y los colaboradores</gray>
aboutLicense=<gray>Licencia: GNU General Public License v3.0 (GPL-3.0)</gray>
aboutGithub=<gray>GitHub: <white>https://github.com/milkteamc/autotreechop</white></gray>
aboutModrinth=<gray>Modrinth: <white>https://modrinth.com/plugin/autotreechop</white></gray>
alreadyEnabled=<yellow>AutoTreeChop está activado.</yellow>
alreadyDisabled=<yellow>AutoTreeChop está desactivado.</yellow>
