blocks-broken=<gray>Tu as cassé {current_blocks}/{max_blocks} blocs aujourd'hui.</gray>
consoleName=console
disabled=<yellow>AutoTreeChop désactivé.</yellow>
disabledByOther=<yellow>AutoTreeChop désactivé par {player}.</yellow>
disabledForOther=<yellow>AutoTreeChop désactivé pour {player}</yellow>
enabled=<green>AutoTreeChop activé.</green>
enabledByOther=<green>AutoTreeChop activé par {player}</green>
enabledForOther=<green>AutoTreeChop activé pour {player}</green>
hitmaxblock=<red>Tu as atteint ta limite quotidienne de destruction de blocs.</red>
hitmaxusage=<red>Tu as atteint ta limite d'utilisation quotidienne.</red>
no-permission=<red>Tu n'as pas la permission de faire ça.</red>
usage=<gray>Tu as utilisé AutoTreeChop {current_uses}/{max_uses} fois aujourd'hui.</gray>
noResidencePermissions=<red>Tu n'as pas la permission d'utiliser AutoTreeChop ici.</red>
stillInCooldown=<yellow>Tu es encore en temps de recharge ! Réessaie après {cooldown_time} secondes.</yellow>
only-players=<red>Cette commande peut seulement être utilisée par les joueurs.</red>
confirmationRequiredIdle=<yellow>AutoTreeChop n'a pas été récemment utilisé. Coupe une nouvelle bûche (ou <white>/atc confirm</white>) avant <white>{timeout}s</white> pour confirmer.</yellow>
confirmationSuccess=<green>Confirmation réussie. AutoTreeChop est maintenant actif.</green>
noPendingConfirmation=<red>Il n'y a pas de confirmation d'AutoTreeChop en attente.</red>
sneakEnabled=<green>AutoTreeChop activé en étant accroupi.</green>
sneakDisabled=<yellow>AutoTreeChop désactivé en n'étant plus accroupi .</yellow>
aboutHeader=<green><bold>AutoTreeChop</bold></green><gray> - <aqua>v{version}</aqua> par l'équipe MilkTeaMC et les contributeurs</gray>
aboutLicense=<gray>Licence : GNU General Public License v3.0 (GPL-3.0)</gray>
aboutGithub=<gray>GitHub: <white>https://github.com/milkteamc/autotreechop</white></gray>
aboutModrinth=<gray>Modrinth: <white>https://modrinth.com/plugin/autotreechop</white></gray>
confirmationRequiredNoLeaves=<yellow>Pas de feuillage détecté à proximité. Cette bûche a pu être placée par un joueur. Couper une nouvelle bûche (ou <white>/atc confirm</white>) avant <white>{timeout}s</white> pour confirmer.</yellow>
confirmationRequiredBoth=<yellow>AutoTreeChop n'a pas été récemment utilisé et aucun feuillage n'a été détecté à proximité. Coupez une nouvelle bûche (ou <white>/atc confirm</white>) avant <white>{timeout}s</white> pour confirmer.</yellow>
alreadyEnabled=<yellow>AutoTreeChop est déjà activé.</yellow>
alreadyDisabled=<yellow>AutoTreeChop est déjà désactivé.</yellow>
