noResidencePermissions=<red>Non hai i permessi per usare AutoTreeChop qui.</red>
enabled=<green>AutoTreeChop attivato.</green>
disabled=<yellow>AutoTreeChop disattivato.</yellow>
enabledByOther=<green>AutoTreeChop è stato attivato da {player}.</green>
enabledForOther=<green>AutoTreeChop è stato attivato per {player}.</green>
disabledByOther=<yellow>AutoTreeChop è stato disattivato da {player}.</yellow>
disabledForOther=<yellow>AutoTreeChop è stato disattivato per {player}.</yellow>
no-permission=<red>Non hai i permessi per effettuare questa azione.</red>
only-players=<red>Questo comando può essere usato soltanto dai giocatori.</red>
hitmaxusage=<red>Hai raggiunto il tuo limite di utilizzo giornaliero.</red>
hitmaxblock=<red>Hai raggiunto il tuo limite giornaliero di blocchi distrutti.</red>
usage=<gray>Utilizzi giornalieri di AutoTreeChop: {current_uses}/{max_uses}</gray>
blocks-broken=<gray>Blocchi distrutti oggi: {current_blocks}/{max_blocks}</gray>
stillInCooldown=<yellow>AutoTreeChop è in cooldown. Per favore attendi {cooldown_time} secondi.</yellow>
confirmationRequiredIdle=<yellow>AutoTreeChop non è stato utilizzato di recente. Distruggi un tronco (o digita <white>/atc confirm</white>) entro <white>{timeout} s</white> per confermare.</yellow>
confirmationRequiredNoLeaves=<yellow>Non ci sono foglie rilevate nelle vicinanze. Questo tronco potrebbe essere stato piazzato da un giocatore. Taglia ancora (o digita <white>/atc confirm</white>) entro <white>{timeout} s</white> per confermare.</yellow>
confirmationRequiredBoth=<yellow>AutoTreeChop non è stato utilizzato di recente e non ci sono foglie rilevate nelle vicinanze. Taglia ancora (o digita <white>/atc confirm</white>) entro <white>{timeout} s</white> per confermare.</yellow>
confirmationSuccess=<green>Conferma effettuata. AutoTreeChop è ora attivo.</green>
noPendingConfirmation=<red>Non ci sono richieste di conferma di AutoTreeChop in sospeso.</red>
sneakEnabled=<green>AutoTreeChop è stato attivato durante l'accovacciamento.</green>
sneakDisabled=<yellow>AutoTreeChop disattivato dopo aver interrotto l'accovacciamento.</yellow>
consoleName=console
aboutHeader=<green><bold>AutoTreeChop</bold></green><gray> - <aqua>v{version}</aqua>di MilkTeaMC team e collaboratori</gray>
aboutLicense=<gray>Licenza: GNU General Public License v3.0 (GPL-3.0)</gray>
aboutGithub=<gray>GitHub: <white>https://github.com/milkteamc/autotreechop</white></gray>
aboutDiscord=<gray>Discord: <white>https://discord.gg/uQ4UXANnP2</white></gray>
aboutModrinth=<gray>Modrinth: <white>https://modrinth.com/plugin/autotreechop</white></gray>
