blocks-broken=<prefix>Вы срубили {current_blocks}/{max_blocks} блоков сегодня.</prefix>
consoleName=Консоль
disabled=<prefix_negative>Автоматическая рубка отключена.</prefix_negative>
disabledByOther=<prefix_negative>Автоматическая рубка отключена игроком {player}.</prefix_negative>
disabledForOther=<prefix_negative>Автоматическая рубка отключена для {player}.</prefix_negative>
enabled=<prefix>Автоматическая рубка включена.</prefix>
enabledByOther=<prefix>Автоматическая рубка включена игроком {player}.</prefix>
enabledForOther=<prefix>Автоматическая рубка включена для {player}.</prefix>
hitmaxblock=<prefix_negative>Вы достигли дневного лимита блоков для автоматической рубки.</prefix_negative>
hitmaxusage=<prefix_negative>Вы достигли дневного лимита использования автоматической рубки.</prefix_negative>
no-permission=<prefix_negative>У вас нет разрешения на это действие.</prefix_negative>
usage=<prefix>Вы использовали автоматическую рубку {current_uses}/{max_uses} раз сегодня.</prefix>
noResidencePermissions=<prefix_negative>У вас нет прав на использование автоматической рубки здесь.</prefix_negative>
stillInCooldown=<prefix_negative>Перезарядка авторубки. Откатится через {cooldown_time} секунд.</prefix_negative>
only-players=<prefix_negative>Эта команда может быть использована только игроками.</prefix_negative>
sneakEnabled=<prefix>Автоматическая рубка деревьев включается тайком.</prefix>
sneakDisabled=<prefix_negative>Автоматическая рубка деревьев отключена путем остановки подкрадывания.</prefix_negative>
confirmationRequiredIdle=<yellow>Автоматическая рубка не была использован недавно. Срубите бревно снова (или <white>/atc confirm</white>) в течение <white>{timeout}с</white> для подтверждения.</yellow>
confirmationRequiredNoLeaves=<yellow>Не было обнаружено листьев поблизости. Это бревно возможно поставлено игроком. Срубите снова (или <white>/atc confirm</white>) в течение <white>{timeout}с</white> для подтверждения.</yellow>
confirmationRequiredBoth=<yellow>Автоматическая рубка не была использована недавно и не обнаружено листьев поблизости. Срубите снова (или <white>/atc confirm</white>) в течение <white>{timeout}с</white> для подтверждения.</yellow>
confirmationSuccess=<green>Подтверждение успешно. Автоматическая рубка теперь активна.</green>
noPendingConfirmation=<red>Сейчас не требуется подтверждение для автоматической рубки.</red>
alreadyEnabled=<yellow>Автоматическая рубка уже включена.</yellow>
alreadyDisabled=<yellow>Автоматическая рубка уже выключена.</yellow>
aboutHeader=<green><bold>AutoTreeChop</bold></green><gray> - <aqua>v{version}</aqua> от команды MilkTeaMC и контрибьюторов</gray>
aboutLicense=<gray>Лицензия: Стандартная общественная лицензия GNU v3.0 (GPL-3.0)</gray>
aboutGithub=<gray>GitHub: <white>https://github.com/milkteamc/autotreechop</white></gray>
aboutModrinth=<gray>Modrinth: <white>https://modrinth.com/plugin/autotreechop</white></gray>
