name: AutoTreeChop
version: '${version}'
main: org.milkteamc.autotreechop.AutoTreeChop
api-version: 1.17
author: Maoyue
description: A auto tree chopping plugin for milkteamc
softdepend: [ PlaceholderAPI, Residence, Lands, WorldGuard ]
folia-supported: true

permissions:
  autotreechop.use:
    default: true
  autotreechop.replant:
    default: true
  autotreechop.leaves:
    default: true
  autotreechop.vip:
    default: op
  autotreechop.updatechecker:
    default: op
  autotreechop.other:
    default: op
  autotreechop.reload:
    default: op
