name: "🐛 Bug Report"
description: Create a new ticket for a bug.
title: "[BUG] - <title>"
labels: [
  "bug"
]
body:
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: Please enter an explicit description of your issue
      placeholder: Short and explicit description of your incident...
    validations:
      required: true
  - type: textarea
    id: reprod
    attributes:
      label: "Reproduction steps"
      description: Please enter an explicit description of your issue
      placeholder: |
        1. ....
        2. ....
        3. ....
        4. See error
      render: bash
    validations:
      required: true
  - type: textarea
    id: config
    attributes:
      label: "Your Config"
      description: Please copy and paste your `plugins/AutoTreeChop/config.yml` file
      render: bash
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: "Logs"
      description: Please copy and paste any relevant log output.
      render: bash
    validations:
      required: false
  - type: textarea
    id: version
    attributes:
      label: "Server Version"
      description: Please paste the output of `version` command in your server console.
      placeholder: |
        [18:58:22 INFO]: Checking version, please wait...
        [18:58:22 INFO]: This server is running Folia version 1.21.6-6-ver/1.21.6@e4b0ae9 (2025-06-29T03:17:11Z) (Implementing API version 1.21.6-R0.1-SNAPSHOT)
        You are running the latest version
      render: bash
    validations:
      required: true
  - type: textarea
    id: plugins
    attributes:
      label: "Server Plugins"
      description: Please paste the output of `plugins` command in your server console.
      placeholder: |
        [19:01:39 INFO]: ℹ Server Plugins (3):
        [19:01:39 INFO]: Bukkit Plugins:
        [19:01:39 INFO]:  - AutoTreeChop, CatchBall, ViaVersion
      render: bash
    validations:
      required: true
  - type: textarea
    id: other
    attributes:
      label: "Other Info (If needed)"
      description: If you think there is other relevant information, please let us know here.
      placeholder: |
        Java version: 22
        OS: Arch Linux x86_64
        etc.
      render: bash
    validations:
      required: false
