package org.milkteamc.autotreechop.hooks;

import com.gmail.nossr50.mcMMO;
import com.gmail.nossr50.util.blockmeta.UserBlockTracker;
import org.bukkit.block.Block;

/**
 * Helper for interacting with mcMMO's placed block tracking system.
 * <p>
 * mcMMO keeps track of blocks players place via its {@link UserBlockTracker}.
 * This class exposes a simple {@link #isNatural(Block)} check so our plugin can
 * ignore player built structures when chopping trees.
 */
public class McMMOHook {

    private final UserBlockTracker tracker;

    public McMMOHook() {
        this.tracker = mcMMO.getUserBlockTracker();
    }

    /**
     * Determine if the given block is considered naturally generated by mcMMO.
     *
     * @param block the block to test
     * @return {@code true} if mcMMO treats the block as natural
     */
    public boolean isNatural(Block block) {
        if (tracker == null) {
            // If mcMMO failed to supply a tracker, default to natural
            return true;
        }

        // mcMMO marks player placed blocks as "ineligible" for XP. A block is
        // natural if it is still eligible.
        return tracker.isEligible(block);
    }
}
